import { PUBLIC_CHAPTER_EMAIL, PUBLIC_CHAPTER_GITHUB, PUBLIC_CHAPTER_INSTAGRAM, PUBLIC_CHAPTER_INSTITUTION, PUBLIC_CHAPTER_LINKEDIN, PUBLIC_CHAPTER_NAME, PUBLIC_CHAPTER_TWITTER, PUBLIC_CHAPTER_URL } from "$env/static/public";

export const gkssConfig = {
  name: PUBLIC_CHAPTER_NAME,
  url: PUBLIC_CHAPTER_URL,
  institution: PUBLIC_CHAPTER_INSTITUTION,
  socials: {
    email: PUBLIC_CHAPTER_EMAIL,
    twitter: PUBLIC_CHAPTER_TWITTER,
    linkedin: PUBLIC_CHAPTER_LINKEDIN,
    instagram: PUBLIC_CHAPTER_INSTAGRAM,
    github: PUBLIC_CHAPTER_GITHUB,
  }
};
